In [1]:
import numpy as np
import statistics as stats
from scipy.stats import skew,kurtosis
import random
from scipy import stats

#### Quantile :

In [2]:
x = [10,20,30,40,50,60,70]
print(x)

[10, 20, 30, 40, 50, 60, 70]


In [3]:
q25 = np.quantile(x, 0.25)
q50 = np.quantile(x, 0.5)
q75 = np.quantile(x, 0.75)
print(q25,q50,q75)

25.0 40.0 55.0


#### IQR ( Interquartile Range) :

In [4]:
Q1 = np.percentile(x,25)
Q3 = np.percentile(x,75)
IQR = Q3-Q1
print(IQR)

30.0


#### Outliers :

In [15]:
x2 = [-150,-100,-90,-25,-5,-1,10,20,30,40,50,60,70,500,1000]
Q1 = np.percentile(x2,25)
Q3 = np.percentile(x2,75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR
print(Q1,Q3,IQR,lower_bound,upper_bound)

-15.0 55.0 70.0 -120.0 160.0


In [12]:
outliers = [x for x in x2 if x < lower_bound or x > upper_bound]
print(outliers)

[-150, 500, 1000]


#### Kurtosis and Skewness :

In [6]:
x3 = np.array([10,20,30,15,18,30,35,50])     # =3:Mesokurtic, >3:Leptokurtic, <3:Plateokurtic
sk = skew(x3)                                # >0:right skewed, <0:left skewed, =0:symmetic
ku = kurtosis(x3)
print(sk,ku)

0.6056789721537372 -0.5026082044432152


#### Covariance :

In [17]:
x = np.array([10,20,30,40,50])        # Covariance measures how two variables changes together.
y = np.array([5,25,35,45,65])         # if they increase or decrease together covariance is positive.
cov_matrix = np.cov(x,y)              # if one increase while other decrease covariance is negative.
print(cov_matrix)                      # if they are unrelated covariance is close to zero.

[[250. 350.]
 [350. 500.]]


In [18]:
print('Covariance between x and y :', cov_matrix[0,1])

Covariance between x and y : 350.0


#### Correlation :

In [21]:
x  = [10,20,30,40,50]               # correlation letts how strongly two variables move together.
y = [20,30,40,50,60]                # it is scale independent(always between -1 and 1)
col = np.corrcoef(x, y)
print(col)
print('Correlation between x and y:', col[0,1])

[[1. 1.]
 [1. 1.]]
Correlation between x and y: 1.0


#### Hypothesis test :

In [ ]:
# Hypothesis test is a statistical method used to make decision or draw conclusions obout a population based on a sample data.
# alpha = 0.05
# if p_value < alpha
#       print("reject the null hypothesis")
# else:
#       print("fail to reject the null hypothesis")

#### P-value :

In [ ]:
# p-value(probability value) is a number that helps to decide whether to reject the null hypothesis in a hypothesis test.

#### t-test :

In [ ]:
# A t-test checks if two averages are really different or if the difference happened by random chance.

#### One sample test:

In [22]:
data = [52,49,51,50,53,48,47,54,49,50]      # if the sample mean is different from a known value.testing if mean is equal to 50.
data

[52, 49, 51, 50, 53, 48, 47, 54, 49, 50]

In [27]:
t_stat, p_value = stats.ttest_1samp(data, 50)
print(t_stat)
print(p_value)

0.42857142857142455
0.6783097418055826


In [ ]:
# result: p_value > 0.05 , fail to reject null hypothesis.

#### Two sample test :

In [28]:
group1 = [10,12,11,13,12]              # compares mean of two different groups.
group2 = [14,15,13,16,15]
t_stat, p_value = stats.ttest_ind(group1, group2)
print(t_stat,p_value)

-4.160251471689219 0.003164123781235034


In [ ]:
# result : p_value < 0.05 , reject the null hypothesis.

#### Paired test :

In [29]:
before = [100,102,98,97,101]      # compares mean from the same group at two different times.
after = [105,107,100,102,106]
t_stat, p_value = stats.ttest_rel(before, after)
print(t_stat, p_value)

-7.333333333333334 0.0018405080271155973


In [ ]:
# result: p_value < 0.05  , reject the null hypothesis.

#### ANOVA/F test :

In [30]:
group1 =[50,52,53,49,51]         # used to check if three or more group means are significantly different from each other.
group2 = [60,62,59,58,61]
group3 = [70,68,69,71,72]
f_stat, p_value = stats.f_oneway(group1,group2,group3)
print('f-statistics:', f_stat)
print('p-value:', p_value)
          

f-statistics: 180.66666666666666
p-value: 1.1028256754466683e-09


In [31]:
# actual p_value is 0.0000000001102852
# result : p_value < 0.05 , reject the null hypothesis

#### Sampling :

In [2]:
population = list(range(1,101))
print(population)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [3]:
sample = random.sample(population, 10)
print(sample)

[29, 73, 72, 36, 56, 46, 64, 67, 35, 44]


In [4]:
data = np.arange(1,101)       # with numpy
print(data)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
sample = np.random.choice(data, size=10, replace=False)
print(sample)

[72  6 56 21 16 33 91  9 15 52]


In [6]:
import pandas as pd

In [8]:
df = pd.DataFrame({
             'id': range(1,21),
             'age': np.random.randint(18,60,20)})              # with pandas
df

id  age
0    1   31
1    2   44
2    3   28
3    4   18
4    5   34
5    6   19
6    7   22
7    8   59
8    9   39
9   10   55
10  11   58
11  12   59
12  13   33
13  14   18
14  15   41
15  16   33
16  17   23
17  18   22
18  19   52
19  20   53

In [9]:
sample_df = df.sample(n=5, random_state=42)
sample_df

id  age
0    1   31
17  18   22
15  16   33
1    2   44
8    9   39

#### Stratified Sampling( by group) :

In [11]:
stratified_sample = df.groupby('age').sample(frac=0.3, random_state=1)
stratified_sample

id  age
3    4   18
6    7   22
15  16   33
11  12   59

#### Systematic Sampling :

In [12]:
k = 5
sys_sample = df.iloc[::k]
print(sys_sample)

    id  age
0    1   31
5    6   19
10  11   58
15  16   33
